rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.5
  - rbx-2
gemfile:
  - gemfiles/rails41.gemfile
  - gemfiles/rails42.gemfile
bundler_args: --no-deployment
script: "bundle exec rake test"
sudo: false
cache:
  bundler: true

branches:
  only: "master"
