rvm:
  - 2.0.0
  - 2.1.6
  - 2.2.2
  - rbx-2
gemfile:
  - gemfiles/rails3.2.gemfile
  - gemfiles/rails4.0.gemfile
  - gemfiles/rails4.1.gemfile
  - gemfiles/rails4.2.gemfile
bundler_args: --no-deployment
script: "bundle exec rake test"
sudo: false
cache:
  bundler: true
branches:
  only: master
matrix:
  exclude:
    - rvm: 2.2.2
      gemfile: gemfiles/rails3.2.gemfile
    - rvm: rbx-2
      gemfile: gemfiles/rails3.2.gemfile
